### ISSUE TITLE
Yarn PnP compatibility

### ISSUE THREAD

**Issue by stellarhoof** [react-cosmos/react-cosmos#946]
### What's wrong?

When using yarn plug n play, I cannot run cosmos since it tries to import the `debug` package without having it declared in its dependencies (although I don't know if this is because yarn is more strict with respect to dependencies). I cloned the react-cosmos repo and added `debug` to `packages/react-cosmos/package.json` and it worked.

`react-cosmos-voyager2` is missing `lodash`

**Comment by stellarhoof** [comment]
Now `packages/react-cosmos` is missing `slash`. It'd be useful if the entire repo was ran through yarn pnp to figure out missing ones since it has stricter dependency requirements.

**Comment by skidding** [comment]
@stellarhoof Thanks for reporting these!

What's the best way to check? I just ran `yarn --pnp` in the Cosmos repo root and it didn't complain.

**Comment by skidding** [comment]
These issues should be fixed in `v5.0.0-alpha.2` (presuming you're interested in Cosmos Next).

But let me know if you have an answer to my previous question. I'd like to include a small CI step to prevent this from happening in the future. Thanks!

**Comment by stellarhoof** [comment]
Getting there, but there are still missing deps. To reproduce, make an empty directory with a stub `package.json` like
```
{
  "name": "stub",
  "version": "0.0.0",
  "installConfig": {
    "pnp": true
  },
  "scripts": {},
  "dependencies": {
    "react-cosmos": "5.0.0-alpha.2"
  }
}
```
Then do `yarn install` followed by `yarn cosmos`

**Comment by skidding** [comment]
Hmm, maybe I'm not grasping how pnp works, but here's an error I don't understand.

> ERROR in /Users/ovidiu/Library/Caches/Yarn/v4/npm-react-cosmos-5.0.0-alpha.2-f4ccdad5b29e38ed61b443fe03a3b3f7e0c28201/node_modules/react-cosmos/dist/plugins/webpack/client/errorOverlay/reactErrorOverlay.js
Module not found: Error: **Can't resolve 'react-error-overlay'** in '/Users/ovidiu/Library/Caches/Yarn/v4/npm-react-cosmos-5.0.0-alpha.2-f4ccdad5b29e38ed61b443fe03a3b3f7e0c28201/node_modules/react-cosmos/dist/plugins/webpack/client/errorOverlay'

The `react-cosmos` package _does_ have `react-error-overlay` as a dependency.

> cat /Users/ovidiu/Library/Caches/Yarn/v4/npm-react-cosmos-5.0.0-alpha.2-f4ccdad5b29e38ed61b443fe03a3b3f7e0c28201/node_modules/react-cosmos/package.json
{
  "name": "react-cosmos",
  "version": "5.0.0-alpha.2",
  "description": "CLI for running React Cosmos inside webpack-powered apps",
  "repository": "https://github.com/react-cosmos/react-cosmos/tree/master/packages/react-cosmos",
  "license": "MIT",
  "main": "index.js",
  "dependencies": {
    "chokidar": "^2.1.5",
    "debug": "^4.1.1",
    "express": "^4.16.4",
    "fs-extra": "^7.0.1",
    "glob": "^7.1.3",
    "http-proxy-middleware": "^0.19.1",
    "import-from": "^3.0.0",
    "launch-editor": "^2.2.1",
    "lodash": "^4.17.11",
    "micromatch": "^4.0.2",
    "query-string": "^6.4.2",
    "react-cosmos-fixture": "^5.0.0-alpha.2",
    "react-cosmos-playground2": "^5.0.0-alpha.2",
    "react-cosmos-shared2": "^5.0.0-alpha.2",
    **"react-error-overlay": "^5.1.5",**
    "resolve-from": "^5.0.0",
    "slash": "^2.0.0",
    "socket.io": "^2.2.0",
    "util.promisify": "^1.0.0",
    "webpack-dev-middleware": "^3.6.2",
    "webpack-hot-middleware": "^2.24.4",
    "yargs": "^13.2.2"
  },
  "bin": {
    "cosmos": "./bin/cosmos.js",
    "cosmos-export": "./bin/cosmos-export.js",
    "cosmos-native": "./bin/cosmos-native.js"
  },
  "gitHead": "36383e60e13fccdcb098db0426ab36b35c34b73a"
}

Any ideas?

**Comment by stellarhoof** [comment]
No ideas :( I get lots of errors of that kind on doing `yarn cosmos` as well. One thing that comes to mind is that there might be some problems if you're using only `tsc` to transpile ts instead of `babel` (https://yarnpkg.com/en/docs/pnp/getting-started)

**Comment by skidding** [comment]
tsc compilation is likely the issue. I would be happy to solve this issue but I'd also hate to complicate package compilation only for a Yarn feature...

Subscribed to https://github.com/Microsoft/TypeScript/issues/18896 in the meantime to stay informed and renamed this issue.

**Comment by stellarhoof** [comment]
Yes, reworking your infra is not worth it if that's the problem. Thanks for looking into it.

**Comment by marco-silva0000** [comment]
Any updates on this issue? I'm looking into using this lib on my projects specifically if it works with yarn PNP, because I come from a painfully attempt at using it with storybook with no success. 

Regarding integration with TS, you have this plugin https://github.com/arcanis/ts-pnp
With webpack, you have this plugin: https://github.com/arcanis/pnp-webpack-plugin

My team will try to make this lib working with PNP, and we will report on the progress here.

**Comment by skidding** [comment]
@marco-silva0000 I'm working on migrating the monorepo to building using Babel instead of `tsc` (https://github.com/react-cosmos/react-cosmos/pull/983.)  and as a by product this issue with PnP might go away. I'm caught up with other stuff at the moment but I estimate it should take <1 week for me to ship this change.

**Comment by skidding** [comment]
@stellarhoof @marco-silva0000 I just published `react-cosmos@5.0.0-alpha.14` with packages built using Babel. Can you please try again to see if the PNP issue still exists?

**Comment by marco-silva0000** [comment]
@pmfgomes got it working on a PNP project just with pnp-webpack-plugin, because our project doesn't use TS.

**Comment by marco-silva0000** [comment]
We had a few problems when using cosmos with PNP of yarn2, you can see it on this repo
https://github.com/pmfgomes/test-react-cosmos

The above #989 should fix the fist hurdle.

We still have some issues, mostly with webpack-html-plugin I believe, but I thing this is moving on the right track

**Comment by skidding** [comment]
Good news!

I've got Cosmos to work with Yarn PnP. For me, it was only about [configuring `pnp-webpack-plugin`](https://github.com/react-cosmos/pnp-example/blob/350d7f7687890c2d123dab7bb95a645c6a74338c/webpack.override.js).  Check out the [php-example](https://github.com/react-cosmos/pnp-example).

Can anyone else confirm this? I'm on `yarn@1.17.3` and `react-cosmos@5.0.0-beta.2` btw. @marco-silva0000 can you try this with Yarn v2?

**Comment by brianespinosa** [comment]
We should hopefully have our fairly large monorepo application working with PNP by the end of January. I'll circle back by then to report any issues.

**Comment by hydrosquall** [comment]
I just tried Cosmos out with Yarn 2 on an internal project after running into issues with Storybook ( https://github.com/storybookjs/storybook/issues/9527 ), and am happy to report that this is working out of the box for us! This is using `react-cosmos@5.0.6`.

**Comment by hydrosquall** [comment]
Update: a caveat is that this appears works fine with `jsx`, but I'm getting about 20 different `Import Declaration Conflicts` warnings that are all shaped slightly like this for every declaration, looking something like this:

```
.yarn/cache/react-cosmos-shared2-npm-5.0.4-3bc9bd1e3b-1.zip/node_modules/react-cosmos-shared2/dist/fixtureState/index.d.ts  error TS2440: Import declaration conflicts with local declaration of 'FixtureStateClassState'
```

**Comment by skidding** [comment]
@IgnusG PnP compatibility should be fixed in v6.

- Please check out the [migration guide](https://github.com/react-cosmos/react-cosmos/blob/main/docs/MIGRATION_V6.md) if you want to try it out. 
- Also updated the [pnp-example](https://github.com/react-cosmos/pnp-example) repo and created a [GitHub Actions workflow](https://github.com/react-cosmos/react-cosmos/blob/6aefc11752c44ad442dfeccd47858f59aa7cf605/.github/workflows/test-pnp.yml) that makes sure Cosmos still works well in that repo after every commit.
- In case I missed something let me know and we'll strengthen the example repo and automated workflow to prevent PnP issues from cropping up again in the future.
